export const prologos = {
  es: [
  
  "","","",
  "Este no es un libro cualquiera.",
  "Es una obra colectiva. Viva.",
  "Un grito escrito por muchas manos, muchas conciencias, muchas almas que no han querido ser cómplices del silencio.",
  "Este libro no es solo un relato.",
  "Es un testimonio.",
  "Es un deber.",
  "Es una promesa a quienes vendrán después de nosotros: nuestros hijos, nuestros nietos, nuestros pueblos.",
  "No quiero que este libro se lea como una novela más.",
  "Quiero que sea un documento vivo, crudo, sincero, de lo que hemos vivido.",
  "No desde los medios.",
  "No desde las voces del poder.",
  "Sino desde la piel, desde la conciencia, desde la dignidad de quienes, sin ser palestinos, se han sentido parte de esta lucha.",
  "Porque este libro no está escrito por las víctimas directas del genocidio, ni por refugiados que han perdido sus hogares, ",
  "ni siquiera necesariamente por quienes han pisado Gaza o Cisjordania.",
  "Este libro está escrito por personas de todo el mundo:",
  "personas que se han movilizado, que han alzado la voz, que han marchado, que han financiado, que han educado, que han acompañado ",
  "al pueblo palestino desde sus propias realidades.",
  "Musulmanes, cristianos, ateos, agnósticos, laicos.",
  "Personas de todas las razas, ideologías, géneros y lenguas.",
  "Gente sencilla, pero con un compromiso inmenso.",
  "Gente que no podía seguir mirando hacia otro lado.",
  "",
  "Lo único que los une es una misma certeza:",
  "la causa palestina es la causa más noble de nuestra era.",
  "Este libro no lo han escrito expertos, ni políticos, ni instituciones.",
  "Lo han escrito personas.",
  "Personas que han actuado, que han alzado la voz, que han sostenido, que han llorado.",
  "Personas que no han estado allí, tal vez,",
  "pero que no han podido permanecer indiferentes.",
  "Y que han elegido contar, sentir y no olvidar.",
  "Porque lo que ha ocurrido —lo que ocurre hoy y seguirá ocurriendo si no lo detenemos— está siendo contado por el mismo verdugo.",
  "Por quienes masacran, por quienes oprimen, por quienes se esconden detrás de palabras grandes y discursos vacíos para justificar ",
  "el asesinato de un pueblo.",
  "No queremos que le pase a Palestina lo que ya les ocurrió a tantos pueblos antes.",
  "Como les pasó a los pueblos indígenas de América.",
  "Sus historias, su resistencia, su sabiduría… todo ha sido contado desde la mirada del conquistador, del genocida, del invasor.",
  "Y hoy, siglos después, seguimos conociendo su historia a través de quienes los exterminaron.",
  "Eso no puede volver a pasar.",
  "Este libro nace precisamente para evitarlo.",
  "Nace para ser un documento vivo.",
  "Un refugio de verdad.",
  "Un testigo de lo que fue.",
  "Para que mañana, cuando muchos lo nieguen, lo disfracen, lo reinventen,",
  "haya al menos una voz —entre muchas otras voces que merecen ser escuchadas— que diga:",
  "nosotros no fuimos palestinos, pero no fuimos indiferentes.",
  "Nosotros vimos, sentimos y actuamos.",
  "Este libro no pretende hablar por todos.",
  "Cada persona tiene su historia, su herida, su manera de ver y sentir.",
  "Incluso entre quienes estamos del mismo lado, no hay una sola versión.",
  "Pero lo que sí nos une es el amor inmenso por la causa palestina,",
  "el rechazo a la injusticia",
  "y la certeza de que guardar silencio sería traicionar todo aquello en lo que creemos.",
  "Aquí comienza este camino.",
  "Un camino que no tiene fin.",
  "Porque este es un libro colectivo, pero también es un libro vivo.",
  "Un libro que no se cerrará mientras Palestina siga sufriendo.",
  "Un libro que no acabará hasta que Palestina vuelva a ser lo que fue,",
  "desde el río hasta el mar.",
  "Hasta que los palestinos recuperen su tierra, su dignidad, su libertad.",
  "Mientras haya causa, este libro seguirá vivo.",
  "Cada testimonio que aquí se recoge es un latido.",
  "Cada palabra, un impulso.",
  "Latidos de esperanza no es solo un libro.",
  "Es el latido de las almas puras de esta humanidad.",
  "Cada acto narrado, una sacudida del corazón colectivo.",
  "Cada palabra escrita, una pequeña llama que no quiere apagarse.",
  "El corazón es Gaza.",
  "Y mientras Gaza siga latiendo, la humanidad no estará perdida.",
  "Pero si ese corazón se detiene…",
  "habremos dejado de ser libres.",
  "Habremos dejado de ser humanos.",
  "Este libro es un latido vivo.",
  "Y seguirá latiendo mientras haya una causa por la que luchar,",
  "mientras haya una injusticia que denunciar,",
  "mientras quede alguien que no quiera callar.",
  "“Porque los grandes cambios no siempre nacen de gobiernos, ni de discursos, ni de organizaciones poderosas.",
  "A veces, las hazañas más significativas brotan de pequeños actos,",
  "realizados en silencio,",
  "desde la soledad,",
  "desde la escasez,",
  "desde la incertidumbre.",
  "Actos sencillos.",
  "Hechos por personas comunes.",
  "Sin certezas, sin garantías, sin saber si servirán de algo o si simplemente se perderán en el vacío.",
  "Pero aun así, se hacen.",
  "Porque nacen de la conciencia,",
  "de la dignidad,",
  "de la necesidad de no ser cómplice.",
  "Y son esos actos —mínimos, anónimos, solitarios—",
  "los que sostienen la esperanza",
  "y construyen el cambio real.”",
  "\"— Abdellah Yahyaoui Azuz —\"",
  "",
  "Pueden asediarles, pueden matar sus cuerpos,",
    "pero no podrán impedir que sus palabras,",
    "sus recuerdos y su esencia viajen por el tiempo… libres.",
    "En Latidos de Esperanza no podría faltar un latido más:",
    "un latido desde Gaza, un refugio para ellos.",
    "Allí encontraréis cartas escritas con las manos,",
    "redactadas por el corazón,",
    "hechas de recuerdos agrietados entre escombros,",
    "manchadas con la sangre de un hijo, un padre",
    "o un amor que solo queda como memoria en noches de soledad."
]
,
  en:  [
     "","","",
    "This is not just any book.",
    "It is a collective work. Alive.",
    "A cry written by many hands, many consciences, many souls who refused to be complicit in silence.",
    "This book is more than a story.",
    "It is a testimony.",
    "A duty.",
    "A promise to those who will come after us: our children, our grandchildren, our peoples.",
    "I do not want this book to be read as just another novel.",
    "I want it to be a living document, raw, honest, of what we have lived.",
    "Not through the media.",
    "Not through the voices of power.",
    "But through the skin, the conscience, the dignity of those who, without being Palestinian, felt part of this struggle.",
    "For this book was not written by the direct victims of genocide, nor by refugees who lost their homes,",
    "nor even necessarily by those who have set foot in Gaza or the West Bank.",
    "This book is written by people from all over the world:",
    "people who mobilized, raised their voices, marched, funded, educated, accompanied",
    "the Palestinian people from their own realities.",
    "Muslims, Christians, atheists, agnostics, secular.",
    "People of every race, ideology, gender, and language.",
    "Ordinary people, yet with an immense commitment.",
    "People who could no longer look away.",
    "",
    "What unites them is one certainty:",
    "the Palestinian cause is the noblest cause of our era.",
    "This book was not written by experts, politicians, or institutions.",
    "It was written by people.",
    "People who acted, who spoke up, who supported, who wept.",
    "People who may not have been there,",
    "but who could not remain indifferent.",
    "And who chose to tell, to feel, and not to forget.",
    "Because what has happened — what is happening now and will continue if we do not stop it —",
    "is being told by the very perpetrator.",
    "By those who massacre, who oppress, who hide behind grand words and empty speeches to justify",
    "the murder of a people.",
    "We do not want Palestine to suffer the fate that befell so many peoples before.",
    "Like the Indigenous peoples of the Americas.",
    "Their stories, their resistance, their wisdom… all told through the eyes of the conqueror, the genocidaire, the invader.",
    "And today, centuries later, we still know their story through those who exterminated them.",
    "This must never happen again.",
    "This book is born precisely to prevent it.",
    "It is born to be a living document.",
    "A sanctuary of truth.",
    "A witness to what was.",
    "So that tomorrow, when many deny it, disguise it, or reinvent it,",
    "there is at least one voice — among many voices that deserve to be heard — saying:",
    "we were not Palestinian, but we were not indifferent.",
    "We saw, felt, and acted.",
    "This book does not speak for everyone.",
    "Each person has their story, their wound, their way of seeing and feeling.",
    "Even among those who share the same cause, there is no single version.",
    "But what unites us is the immense love for the Palestinian cause,",
    "the rejection of injustice",
    "and the certainty that silence would betray everything we believe in.",
    "Here begins this path.",
    "An endless path.",
    "For it is a collective book, but also a living book.",
    "A book that will not close as long as Palestine suffers.",
    "A book that will not end as long as Palestine does not reclaim what it was,",
    "from the river to the sea.",
    "Until Palestinians recover their land, dignity, freedom.",
    "As long as there is a cause, this book will remain alive.",
    "Every testimony collected here is a heartbeat.",
    "Every word, an impulse.",
    "**Beats of Hope** is not just a book.",
    "It is the heartbeat of the pure souls of humanity.",
    "Every act recounted, a shock to the collective heart.",
    "Every written word, a small flame that refuses to go out.",
    "The heart is Gaza.",
    "And as long as Gaza beats, humanity is not lost.",
    "But if this heart stops…",
    "we will have ceased to be free.",
    "We will have ceased to be human.",
    "This book is a living heartbeat.",
    "And it will continue to beat as long as there is a cause to fight for,",
    "as long as there is injustice to denounce,",
    "as long as there is someone who refuses to remain silent.",
    "“For great changes do not always arise from governments, nor speeches, nor powerful organizations.",
    "Sometimes, the most significant acts arise from simple gestures,",
    "done in silence,",
    "from solitude,",
    "from scarcity,",
    "from uncertainty.",
    "Simple acts.",
    "Done by ordinary people.",
    "Without certainty, without guarantees, without knowing if they will matter or be lost in the void.",
    "But they are done anyway.",
    "For they arise from consciousness,",
    "from dignity,",
    "from refusal to be complicit.",
    "And these acts — tiny, anonymous, solitary —",
    "sustain hope",
    "and build true change.”",
    "\"— Abdellah Yahyaoui Azuz —\"",
    "", "They can besiege them, they can kill their bodies,",
    "but they cannot stop their words,",
    "their memories and their essence from traveling through time… free.",
    "In Heartbeats of Hope, there could not be one more heartbeat missing:",
    "a heartbeat from Gaza, a refuge for them.",
    "There you will find letters written by hands,",
    "composed by the heart,",
    "made from memories cracked among rubble,",
    "stained with the blood of a son, a father,",
    "or a love that remains only as a memory in nights of solitude."
  ]
,
  fr: [
     "","","",
    "Ce n’est pas un livre comme les autres.",
    "C’est une œuvre collective. Vivante.",
    "Un cri écrit de nombreuses mains, de nombreuses consciences, de nombreuses âmes qui ont refusé d’être complices du silence.",
    "Ce livre n’est pas seulement un récit.",
    "C’est un témoignage.",
    "Un devoir.",
    "Une promesse à ceux qui viendront après nous : nos enfants, nos petits-enfants, nos peuples.",
    "Je ne veux pas que ce livre soit lu comme un roman de plus.",
    "Je veux qu’il soit un document vivant, brut, sincère, de ce que nous avons vécu.",
    "Pas à travers les médias.",
    "Pas à travers les voix du pouvoir.",
    "Mais à travers la peau, la conscience, la dignité de ceux qui, sans être palestiniens, se sont sentis partie prenante de cette lutte.",
    "Car ce livre n’est pas écrit par les victimes directes du génocide, ni par des réfugiés ayant perdu leur foyer,",
    "ni même nécessairement par ceux qui ont marché sur Gaza ou en Cisjordanie.",
    "Ce livre est écrit par des personnes venues du monde entier :",
    "des personnes qui se sont mobilisées, ont pris la parole, ont marché, ont financé, ont éduqué, ont accompagné",
    "le peuple palestinien depuis leurs réalités propres.",
    "Musulmans, chrétiens, athées, agnostiques, laïcs.",
    "Des personnes de toutes races, idéologies, genres et langues.",
    "Des gens simples, mais porteurs d’un engagement immense.",
    "Des gens qui ne pouvaient plus détourner le regard.",
    "",
    "Ce qui les unit, c’est une certitude :",
    "la cause palestinienne est la cause la plus noble de notre époque.",
    "Ce livre n’a pas été écrit par des experts, des politiciens ou des institutions.",
    "Il a été écrit par des personnes.",
    "Des personnes qui ont agi, qui ont pris la parole, qui ont soutenu, qui ont pleuré.",
    "Des personnes qui n’étaient peut-être pas sur place,",
    "mais qui n’ont pas pu rester indifférentes.",
    "Et qui ont choisi de raconter, de ressentir et de ne pas oublier.",
    "Parce que ce qui est arrivé — ce qui arrive encore aujourd’hui et continuera si nous ne l’arrêtons pas —",
    "est raconté par le même bourreau.",
    "Par ceux qui massacrent, qui oppriment, qui se cachent derrière de grands mots et des discours vides pour justifier",
    "l’assassinat d’un peuple.",
    "Nous ne voulons pas que la Palestine subisse le même sort que tant d’autres peuples auparavant.",
    "Comme les peuples autochtones d’Amérique.",
    "Leurs histoires, leur résistance, leur sagesse… tout a été raconté à travers le regard du conquérant, du génocidaire, de l’envahisseur.",
    "Et aujourd’hui, des siècles plus tard, nous connaissons encore leur histoire par ceux qui les ont exterminés.",
    "Cela ne doit jamais se reproduire.",
    "Ce livre naît précisément pour l’empêcher.",
    "Il naît pour être un document vivant.",
    "Un refuge de vérité.",
    "Un témoin de ce qui fut.",
    "Pour que demain, quand beaucoup nieront, travestiront ou réinventeront la vérité,",
    "il y ait au moins une voix — parmi tant d’autres voix méritant d’être entendues — qui dise :",
    "nous n’étions pas palestiniens, mais nous n’étions pas indifférents.",
    "Nous avons vu, ressenti et agi.",
    "Ce livre ne prétend pas parler pour tous.",
    "Chacun a son histoire, sa blessure, sa façon de voir et de ressentir.",
    "Même parmi ceux qui partagent la même cause, il n’y a pas une seule version.",
    "Mais ce qui nous unit, c’est l’amour immense pour la cause palestinienne,",
    "le rejet de l’injustice",
    "et la certitude que le silence serait trahir tout ce en quoi nous croyons.",
    "Voici le commencement de ce chemin.",
    "Un chemin sans fin.",
    "Car c’est un livre collectif, mais aussi un livre vivant.",
    "Un livre qui ne se fermera pas tant que la Palestine souffrira.",
    "Un livre qui ne s’achèvera pas tant que la Palestine ne retrouvera pas ce qu’elle était,",
    "du fleuve à la mer.",
    "Jusqu’à ce que les Palestiniens récupèrent leur terre, leur dignité, leur liberté.",
    "Tant qu’il y aura une cause, ce livre restera vivant.",
    "Chaque témoignage ici recueilli est un battement.",
    "Chaque mot, une impulsion.",
    "**Battements d’espoir** n’est pas seulement un livre.",
    "C’est le battement des âmes pures de l’humanité.",
    "Chaque acte raconté, un choc pour le cœur collectif.",
    "Chaque mot écrit, une petite flamme qui refuse de s’éteindre.",
    "Le cœur, c’est Gaza.",
    "Et tant que Gaza battra, l’humanité ne sera pas perdue.",
    "Mais si ce cœur s’arrête…",
    "nous aurons cessé d’être libres.",
    "Nous aurons cessé d’être humains.",
    "Ce livre est un battement vivant.",
    "Et il continuera à battre tant qu’il y aura une cause pour laquelle se battre,",
    "tant qu’il y aura une injustice à dénoncer,",
    "tant qu’il restera quelqu’un qui refuse de se taire.",
    "« Car les grands changements ne naissent pas toujours des gouvernements, ni des discours, ni des organisations puissantes.",
    "Parfois, les actes les plus significatifs naissent de gestes simples,",
    "faits en silence,",
    "depuis la solitude,",
    "depuis la rareté,",
    "depuis l’incertitude.",
    "Des actes simples.",
    "Faits par des personnes ordinaires.",
    "Sans certitudes, sans garanties, sans savoir s’ils serviront à quelque chose ou s’ils se perdront dans le vide.",
    "Mais ils sont faits quand même.",
    "Car ils naissent de la conscience,",
    "de la dignité,",
    "du refus d’être complice.",
    "Et ce sont ces actes — minuscules, anonymes, solitaires —",
    "qui soutiennent l’espoir",
    "et construisent le vrai changement. »",
    "\"— Abdellah Yahyaoui Azuz —\"",
    "",
     "Ils peuvent les assiéger, ils peuvent tuer leurs corps,",
    "mais ils ne pourront pas empêcher leurs paroles,",
    "leurs souvenirs et leur essence de voyager à travers le temps… libres.",
    "Dans Battements d'Espoir, il ne pouvait manquer un battement de plus :",
    "un battement venu de Gaza, un refuge pour eux.",
    "Là, vous trouverez des lettres écrites à la main,",
    "rédigées par le cœur,",
    "faites de souvenirs fissurés parmi les décombres,",
    "tachées du sang d'un fils, d'un père,",
    "ou d'un amour qui ne reste que comme mémoire dans les nuits de solitude."
  ],
  ar: [
     "","","",
    "هذا ليس كتاباً عادياً.",
    "إنه عمل جماعي، حيّ، يتنفس.",
    "صرخةٌ سُطّرت بأيدٍ كثيرة، بضمائر يقِظة، وبأرواح أبت أن تكون شريكةً في الصمت.",
    "هذا الكتاب ليس مجرد حكاية.",
    "إنه شهادة،",
    "وواجب،",
    "ووعدٌ لأولئك الذين سيأتون بعدنا: أبناؤنا، أحفادنا، شعوبنا.",
    "لا أريده أن يُقرأ كأي رواية عابرة.",
    "بل كوثيقة حيّة، قاسية وصادقة، تحكي ما عشناه وشهدناه.",
    "لا كما رواه الإعلام،",
    "ولا كما فرضته أصوات السلطة،",
    "بل كما شعرت به جلودنا، وأدركته ضمائرنا، وحفظته كرامتنا، نحن الذين، وإن لم نكن فلسطينيين، شعرنا أن هذه المعركة معركتنا.",
    "فالكتاب لم يكتبه ضحايا الإبادة ، ولا مُهجَّرونَ فقدوا بيوتهم،",
    "ولا بالضرورة من وطئوا غزة أو الضفة بأقدامهم،",
    "بل كتبته أرواح من أصقاع الأرض كلها:",
    "أرواح تحرّكت، هتفت، سارت في الشوارع، أنفقت مما عندها، علّمت، وواست،",
    "أرواح رافقت فلسطين من بعيد، ولكن بقلب قريب.",
    "مسلمون، مسيحيون، ملحدون، علمانيون،",
    "أناس من كل الأعراق، والأفكار، واللغات، والأنواع.",
    "بسطاء، ولكن أصحاب التزام عظيم،",
    "لم يستطيعوا أن يديروا ظهورهم أكثر.",
    "",
    " يوحّدهم يقين واحد:",
    "أن قضية فلسطين هي أقدس قضايا عصرنا.",
    "هذا الكتاب لم يكتبه خبراء، ولا سياسيون، ولا مؤسسات،",
    "كتبه أناس،",
    "أناس هتفوا، وصمدوا، وبكوا،",
    "أناس ربما لم يكونوا هناك،",
    "لكنهم لم يعرفوا طريق اللامبالاة،",
    "فاختاروا أن يكتبوا، أن يشعروا، أن لا ينسوا.",
      "لأن ما جرى ـ ما يجري اليوم إن لم نوقفه فسيستمر  ",
    "و إن لم نوثِّقه فسيُروى  بلسان الجلاد،",
    "بأقلام من يقتلون ويقمعون، من يختبئون خلف الكلمات الفخمة والخطب الجوفاء لتبرير",
    "ذبح شعب بأكمله.",
    "لا نريد لفلسطين أن تُمحى كما مُحيَت ذاكرة شعوب كثيرة قبلها،",
    "كما حدث لشعوب أمريكا الأصليين.",
    "تاريخهم، مقاومتهم، حكمتهم… كلها سُردت بلسان الغازي والقاتل والمستعمر،",
    "واليوم، بعد قرون، ما زلنا نعرف أخبارهم من خلال من أبادهم.",
    "وهذا ما لا يجوز أن يتكرر.",
    "ومن هنا وُلد هذا الكتاب: ليمنع ذلك،",
    "ليكون وثيقة حيّة،",
    "ملجأً للحقيقة،",
    "شهادة على ما كان،",
    "حتى إذا جاء الغد فأنكر كثيرون، وزيّف آخرون، وأعادوا كتابة ما جرى،",
    "تكون هناك على الأقل شهادة صادقة، بين شهادات تستحق أن تُسمع، تقول:",
    "لم نكن فلسطينيين، لكننا لم نكن صامتين،",
    "رأينا، شعرنا، وفعلنا.",
    "هذا الكتاب لا يدّعي أن يتحدث باسم الجميع،",
    "لكل إنسان حكايته، جرحه، طريقته في الفهم والشعور،",
    "حتى بين الذين هم في الصف نفسه، لا توجد رواية واحدة،",
    "لكن ما يجمعنا هو الحب العظيم لفلسطين،",
    "ورفض الظلم،",
    "واليقين بأن الصمت خيانة لكل ما نؤمن به.",
    "هنا يبدأ الطريق.",
    "طريق لا نهاية له.",
    "لأن هذا كتاب جماعي، ولكنه أيضاً كتاب حيّ،",
    "لن يُغلق ما دامت فلسطين تنزف،",
    "ولن يكتمل حتى تعود كما كانت،",
    "من النهر إلى البحر،",
    "حتى يستعيد الفلسطينيون أرضهم وكرامتهم وحريتهم.",
    "ما دامت هناك قضية، سيبقى هذا الكتاب حيّاً.",
    "كل شهادة فيه نبضة،",
    "كل كلمة فيه دفعة،",
    "كتاب \"نبضات الأمل\" ليس مجرد كتاب،",
    "إنه نبض الأرواح الطاهرة في هذه الإنسانية،",
    "كل فعل يُروى فيه، صرخة في قلب الجماعة،",
    "وكل كلمة تُكتب، شعلة صغيرة ترفض أن تنطفئ.",
    "و القلب هي غزة،",
    "ومادام قلب غزة يخفق، فالإنسانية لم تفقد نفسها بعد.",
    "أما إن توقف ذلك القلب…",
    "فسنكون قد فقدنا حريتنا،",
    "وفقدنا إنسانيتنا.",
    "هذا كتاب حيّ، نابض،",
    "وسيبقى ينبض ما دامت هناك قضية تستحق النضال،",
    "وظلم يجب أن يُفضح،",
    "وصوت يرفض الصمت.",
    "فالتغييرات الكبرى لا تولد دائماً من الحكومات، ولا من الخطب، ولا من المؤسسات العاتية،",
    "بل من أفعال صغيرة،",
    "تُنجَز في صمت،",
    "من العزلة،",
    "من الفقر،",
    "ومن قلب الشكوك،",
    "أفعال بسيطة،",
    "يخطوها أناس عاديون،",
    "بلا ضمانات ولا يقين، بلا علم إن كانت ستثمر أو تضيع في الفراغ،",
    "ومع ذلك، يفعلونها،",
    "لأنها تولد من الضمير،",
    "من الكرامة،",
    "من رفض التواطؤ،",
    "وتلك الأفعال ـ الصغيرة، المجهولة، الوحيدة ـ",
    "هي التي تحفظ الأمل،",
    "وتبني التغيير الحقيقي.",
    "\"— عبد الله يحيىوي عزوز —\"",
    "",
      "قد يحاصرونهم، قد يقتلون أجسادهم،",
    " و لكن ",
    "لا حول لهم ولا قوة على إيقاف كلماتهم،",
    "ولا ذكرياتهم،",
    " فالجسد للأرض والكلمات للزّمن،",
    " تسافر فيه حرةً طليقة.",
    "وفي \"نبضات الأمل\" لا يمكننا أن نغفل عن النبضة الأولى:",
    "نبضة من غزة، ملاذ لهم وموئل لقلوبهم.",
    "هناك ستجدون رسائل كتبتها أيادٍ منهكة،",
    "مصاغة بصدق القلب،",
    "حاملة ذكرياتٍ متشققة بين الركام،",
    "ملطخة بدم ابن أو أب،",
    "أو حبٍ مهدورٍ لا تُفارق  ذِكراه."
  ]
};
